GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test2",
  "author": "na",
  "url": "google.com",
  "likes": 0,
  "id": 123
}

###
DELETE http://localhost:3003/api/blogs/614b28c04f21191965ac8e0a

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "salainen",
  "blogs": []
}