GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTUwZDg0OWI2OTdjMDIxMWI0NTc3ZjEiLCJpYXQiOjE2MzI4NTc1ODQsImV4cCI6MTYzMjg2MTE4NH0.e6LOEGh5laAuxQEIoJZ31fg0r56Wx54XVSHnMB-8hzs 

{
  "title": "Microservices, test post 5",
  "author": "Martin Fowler",
  "url": "google.com",
  "likes": 0,
  "user": "6150d849b697c0211b4577f1" 
}

###
DELETE http://localhost:3003/api/blogs/61536edca72bef7fdabbeef3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTUwZDg0OWI2OTdjMDIxMWI0NTc3ZjEiLCJpYXQiOjE2MzI4NTc1ODQsImV4cCI6MTYzMjg2MTE4NH0.e6LOEGh5laAuxQEIoJZ31fg0r56Wx54XVSHnMB-8hzs 

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "salainen",
  "blogs": []
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "mluukkai",
  "password": "salainen"
}
